AWSTemplateFormatVersion: '2010-09-09'
Description: Artemis CodexOps Root Infrastructure (VPC, Subnet, SG, RDS, S3, ECS Cluster, ALB)

Resources:
  CodexOpsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CodexOpsVPC

  CodexOpsSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CodexOpsVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  CodexOpsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CodexOps ECS Security Group
      VpcId: !Ref CodexOpsVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  CodexOpsRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: codexops-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: codexopsadmin
      MasterUserPassword: codexopspassword
      VPCSecurityGroups: [!Ref CodexOpsSG]
      DBName: codexops
      PubliclyAccessible: true
      StorageType: gp2

  CodexOpsS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codexops-assets-${AWS::AccountId}

  CodexOpsCluster:
    Type: AWS::ECS::Cluster

  CodexOpsALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: codexops-alb
      Subnets: [!Ref CodexOpsSubnet]
      SecurityGroups: [!Ref CodexOpsSG]
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4

Outputs:
  CodexOpsVPC:
    Value: !Ref CodexOpsVPC
    Export:
      Name: CodexOpsVPC
  CodexOpsSubnet:
    Value: !Ref CodexOpsSubnet
    Export:
      Name: CodexOpsSubnet
  CodexOpsSG:
    Value: !Ref CodexOpsSG
    Export:
      Name: CodexOpsSG
  CodexOpsCluster:
    Value: !Ref CodexOpsCluster
    Export:
      Name: CodexOpsCluster
  CodexOpsRDSAddress:
    Value: !GetAtt CodexOpsRDS.Endpoint.Address
    Export:
      Name: CodexOpsRDSAddress
  CodexOpsS3Bucket:
    Value: !Ref CodexOpsS3
    Export:
      Name: CodexOpsS3Bucket
  CodexOpsALB:
    Value: !Ref CodexOpsALB
    Export:
      Name: CodexOpsALB
