version: '3'
services:
  code:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    container_name: artemis-vscode
    environment:
      - PASSWORD=changeme
      - TZ=UTC
    ports:
      - "8443:8080"
    volumes:
      - .:/workspace
